name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cats-gazing:${{ github.sha }}

      - name: Clone infra repo
        uses: actions/checkout@v3
        with:
          repository: andriifedotov/cats_gazing_infra
          path: infra
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Deployment image
        run: |
          sed -i "s|image: .*|image: docker.io/andriifedotov/cats-gazing:${GITHUB_SHA}|g" infra/app/deployment.yaml

      - name: Commit changes to infra repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update cats-gazing image to ${{ github.sha }}"
          file_pattern: "app/deployment.yaml"
          cwd: infra
